### ISSUE TITLE
As an Auditor, I can see the list of pending join request from tennis trainer, so that I can approve or reject the request

### ISSUE THREAD

**Issue by ofovweewere** [G5-S4-F21/ACME#16]
- [x] Design screen layout for the Auditor list of pending join requests from the tennis trainer page
- [x] Code the logged in Auditors list of pending join requests from the tennis trainer screen
- [x] Write the Mongo query for the list of pending join request from the tennis trainer info

**Comment by MaxBay2020** [comment]
All functionalities completed
