### ISSUE TITLE
As an Auditor, I can the Validate or reject selected trainer credential, so that I can approve or reject a selected trainer pending request

### ISSUE THREAD

**Issue by ofovweewere** [G5-S4-F21/ACME#18]
- [x] Design confirmation page for the Auditor validation decision
- [x] Code the Auditor validate/reject controller and notify potential tennis trainer of decision
- [x] Write Mongo query to update the record of potential tennis trainer

**Comment by MaxBay2020** [comment]
All functionalities completed
