### ISSUE TITLE
As a Tennis Trainer Seeker, I can see my logged-in home page so that I can either: (i) View a list of his/her favorite trainers, (ii) Search for a lawn trainer, (iii) View or update their profile, (iv) Schedule an appointment with a lawn trainer

### ISSUE THREAD

**Issue by ofovweewere** [G5-S4-F21/ACME#4]
- [ ] Design screen layout for the Tennis Trainer Seeker home page
- [ ] Code Tennis Trainer Seeker controller with 4 routes
- [ ] Write the mongo query for the database related functions

**Comment by skamino** [comment]
Its not pretty but it is there.  For now I think its Ok.
